# Generated by Django 4.2 on 2024-03-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('address', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('score_number', models.IntegerField()),
                ('publish', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=32)),
                ('picture', models.CharField(max_length=64)),
                ('classification', models.CharField(max_length=32)),
                ('intro', models.TextField()),
                ('authorintro', models.TextField(db_column='authorIntro')),
                ('directory', models.TextField()),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowtime', models.DateTimeField()),
                ('returntime', models.DateTimeField()),
            ],
            options={
                'db_table': 'borrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(db_column='bookId', max_length=255)),
            ],
            options={
                'db_table': 'recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('address', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('education', models.CharField(blank=True, max_length=32, null=True)),
                ('major', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
